
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/flex_test
    username: root
    password: 123456

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
      - org.example.dotstart.aop.controller
      - org.example.dotstart.template.controller
      - org.example.dotstart.mybatisflex.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-flex:
  global-config:
    default-page-size: 10
    logic-delete-column: deleted
    key-config:
      key-type: Generator
      value: "snowFlakeId"

